### ISSUE TITLE
Deploy in Production - NPM module broken

### ISSUE THREAD

**Issue by ronaldo-getreveel** [ParsePlatform/parse-dashboard#108]
The tutorial about deploy parse dashboard in production is not working. 
The parse-dashboard npm module seems to be broken.  
The node_modules/parse-dashboard contains only its package.json

#### Environment Setup
Node v5.7.1
OSx El Capitan 10.11
Parse server 2.1.4

#### Steps to reproduce
```
mkdir dashboard && cd dashboard
npm init
npm install --save parse-dashboard
add a start script in your package.json "start": "parse-dashboard --config ./dashboard.json"
npm start
```

#### Logs/Trace

```
> node parse-dashboard --config ./dashboard.json

module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/ronaldo/dev/projects/todayapp-firebase/parse-dashboard'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! TodayAppFirebase@1.0.0 start: `node parse-dashboard --config ./dashboard.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TodayAppFirebase@1.0.0 start script 'node parse-dashboard --config ./dashboard.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the TodayAppFirebase package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node parse-dashboard --config ./dashboard.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs TodayAppFirebase
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls TodayAppFirebase
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ronaldo/dev/projects/todayapp-firebase/npm-debug.log

```

**Comment by drew-gross** [comment]
Whoops, the npm package hasn't been published. I've removed that section of the readme. In the meantime, we are discussing how to best work with npm in #102
