### ISSUE TITLE
SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by Jinoooo** [ParsePlatform/parse-dashboard#186]
**> git clone https://github.com/ParsePlatform/parse-dashboard.git**
**> cd parse-dashboard**
**> npm install**
parse-dashboard@1.0.5 prepublish /Users/Parse/parse-dashboard
webpack --config webpack/publish.config.js --progress
/Users/Parse/parse-dashboard/webpack/plugins/svg-prep.js:10
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Parse/parse-dashboard/webpack/base.config.js:11:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

** Versions**
node: 0.12.7 (on MacBook)
npm: 2.11.3
parse-server: latest (Mar. 26)

**Comment by Jinoooo** [comment]
brew uninstall node
install node 4.4.1
and that fixed the problem.

**Comment by flovilmart** [comment]
you can also use nvm :)
