### ISSUE TITLE
const path = require('path');

### ISSUE THREAD

**Issue by bschron** [ParsePlatform/parse-dashboard#278]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
I am on OS X and the server is a ubuntu at digital ocean. Just cloned parse-server-example so it must be up to date

#### Steps to reproduce
run parse-dashboard --appId **** --masterKey *** --serverURL "https://***:1337/parse" --appName Bigu

#### Logs/Trace
/usr/local/lib/node_modules/parse-dashboard/Parse-Dashboard/index.js:10
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/parse-dashboard/bin/parse-dashboard:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by drew-gross** [comment]
What version of node are you on? If it's lower than 5.7, can you upgrade and see if that fixes the problem?

**Comment by drew-gross** [comment]
No response in many days, closing.
