### ISSUE TITLE
res.sendStatus is not a function

### ISSUE THREAD

**Issue by tanmays** [ParsePlatform/parse-dashboard#375]
Hello,

Curent setup: 

parse-server v2.2.10
parse-dashboard v1.0.11
Both as express middleware on same server (**AWS EB**)

Configuration:
```
var ParseDashboard = require('parse-dashboard');
var dashboard = new ParseDashboard({
  "apps": [
    {
      "serverURL": "http://xxx.com/parse",
      "appId": "xxx",
      "masterKey": "xxx",
      "appName": "xxx"
    }
  ],
  "users": [
    {
      "user":"xxx",
      "pass":"xxx"
    }
  ]
});

// make the Parse Dashboard available at /dashboard
app.use('/dashboard', dashboard);
```

Error log:
```
TypeError: res.sendStatus is not a function
    at /var/app/current/node_modules/parse-dashboard/Parse-Dashboard/app.js:123:18
    at Layer.handle [as handle_request] (/var/app/current/node_modules/parse-dashboard/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/parse-dashboard/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/app/current/node_modules/parse-dashboard/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/parse-dashboard/node_modules/express/lib/router/layer.js:95:5)
    at /var/app/current/node_modules/parse-dashboard/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/var/app/current/node_modules/parse-dashboard/node_modules/express/lib/router/index.js:330:12)
    at next (/var/app/current/node_modules/parse-dashboard/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/var/app/current/node_modules/parse-dashboard/node_modules/express/node_modules/serve-static/index.js:120:7)
    at emitOne (events.js:77:13)
```

**Comment by drew-gross** [comment]
We probably need to bump our express version. If you delete `node_modules` and reinstall, does that fix the issue?

**Comment by drew-gross** [comment]
Hmm never mind, we already have the most recent version in `package.json`.

**Comment by tanmays** [comment]
@drew-gross that was it! My express version was lower. Updating it fixed the issue. Thanks much!

**Comment by jgaull** [comment]
Thanks @tanmays! Your solution worked for me too.
