### ISSUE TITLE
events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by nickjf89** [ParsePlatform/parse-dashboard#401]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=2.1.4 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:4040
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by drew-gross** [comment]
That error means you are already running something else on port 4040. Maybe another copy of the dashboard?

**Comment by bcarlis** [comment]
Thanks Drew! EADDRINUSE does say ADDRess IN USE
I changed 8081 in my example to 7878 that I've used before that I knew was open and all is well.

**Comment by srinivas69** [comment]
Then how to stop the already running dashboard

**Comment by nickjf89** [comment]
> killall -9 node

**Comment by jdmagic21** [comment]
This is interesting because I do have anything that shows that I have another process running on another port. @nickjf89  I've tried to use this command, but there are no processes that can be found. I get this error when I use gulp, "gulp wiredep"

**Comment by robbonghi** [comment]
probably port is already in use so try below code
sudo pkill node

**Comment by Kimosabe2015** [comment]
Having same problem... events.js:160 throw er; // Unhandled 'error' event
Error: listen EADDRINUSE 127.0.0.1:8000

But when I enter sudo or killall command I get :command not found?

How do I download the proper commands for MinGW64 using the MinGW Installation Manager so I can use these commands? And once downloaded how do I install them so they work in Git-Bash?

**Comment by hmuschett** [comment]
run de server on other port

**Comment by BahodirBoydedayev** [comment]
goog job, @drew-gross

**Comment by sanris** [comment]
If the running instances belongs to your project then.

Option #1 
restart the system. 

Option #2 
goto command prompt and try the following command. 

taskkill /f /im node*

- Bagee

**Comment by Cob007** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connection timeout
    at Db.<anonymous> (C:\Users\user\WebstormProjects\loginapp\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (C:\Users\user\WebstormProjects\loginapp\node_modules\mongoose\node_modules\mongodb\lib\db.js:1786:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (C:\Users\user\WebstormProjects\loginapp\node_modules\mongoose\node_modules\mongodb\lib\server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (C:\Users\user\WebstormProjects\loginapp\node_modules\mongoose\node_modules\mongodb-core\lib\topologies\server.js:334:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (C:\Users\user\WebstormProjects\loginapp\node_modules\mongoose\node_modules\mongodb-core\lib\connection\pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (C:\Users\user\WebstormProjects\loginapp\node_modules\mongoose\node_modules\mongodb-core\lib\connection\connection.js:183:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)


please can anyone help me with this error???????????????????????????????????????????????

**Comment by FabMpenge** [comment]
#Cob007 I had the same issue with you during 5 days, so reading all above resolves then I found npm command <b>killall -9 node</b> proposed by #nickjf89. Then the issue was fixed

**Comment by Ronakpatel9994** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
This is error occured when run this code 
[nodemon server.js ]

**Comment by Parveenkmr44** [comment]
Use this code to kill current port process 

sudo lsof -i :8080
sudo kill -9 PID

I am using 8080 and you change it by your port that you are using in your project.

**Comment by bbb324** [comment]
run example

sudo lsof -i :9000
COMMAND   PID    USER   FD      TYPE             DEVICE                      SIZE/OFF      NODE       NAME
Java              716      a           313u   IPv6               0x1111111111111     0t0                    TCP        

then kill it
sudo kill -9 716

**Comment by swetasoorya** [comment]
i am getting this error 
how to resolve this

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND rss.cnn.com rss.cnn.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by bruno-serfe** [comment]
Hi! What about this? anyone knows what's the issue here?

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: </form
    at new HTMLParser (/home/client/node_modules/html-minifier/src/htmlparser.js:236:13)
...
There is more trace code..

**Comment by Hrish33** [comment]
just try to listen in only your main .js 
the one where you configure all the other routers

**Comment by jsteerv** [comment]
Hi, i am having the same error: 

events.js:160
throw er; // Unhandled 'error' event

The command **killall -9 node** returns "node: no process found" and there is nothing using the port 8000, there is a solution?

**Comment by jsteerv** [comment]
- I have enough space on disk
- removing ~/.npm/tmp didn't work
- rm -rf node_modules && npm cache clean && npm installdidn't work
- port is not in use (netstat -nltp)

And restarting doesn't works anymore, i can't run a single example, even in a fresh install

**Comment by flovilmart** [comment]
```
events.js:160
throw er; // Unhandled 'error' event
```

What is the stack trace for the error?

**Comment by jsteerv** [comment]
```
 I  Your site is running at http://localhost:8000
 I  Your graphql debugger is running at http://localhost:8000/___graphql
 WAIT  Compiling...                                                   4:10:15 PM

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/phantom/workspaces/tutorial-part-one/node_modules/fast-glob/node_modules/extglob/node_modules/to-regex/node_modules/regex-not ENOSPC
    at exports._errnoException (util.js:1020:11)
    at FSWatcher.start (fs.js:1443:19)
    at Object.fs.watch (fs.js:1470:11)
    at createFsWatchInstance (/home/phantom/workspaces/tutorial-part-one/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/phantom/workspaces/tutorial-part-one/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/phantom/workspaces/tutorial-part-one/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/phantom/workspaces/tutorial-part-one/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/phantom/workspaces/tutorial-part-one/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/phantom/workspaces/tutorial-part-one/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)

```

It happends on every project

**Comment by flovilmart** [comment]
Not sure where you got your source code, you should probably reach out to the maintainer

**Comment by jsteerv** [comment]
I was following the [tutorial part 2.](https://www.gatsbyjs.org/tutorial/part-two/#gatsby-plugins) It happens when i install this plugin:
`npm install --save gatsby-plugin-typography`

It happens to me twice. I already solve it deleting the tutorial files, including node_modules, npm cache clean, and restarting the pc :+1:  Thanks!

**Comment by alexandra1030** [comment]
I think this happens you are already running something else on port 8080. Maybe another copy of the dashboard? or change the port number.
config/index.js change the port number.
Thanks :)

**Comment by bhumi-patel11** [comment]
@drew-gross  Thanks

**Comment by IlseMagali** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventEmitter.listen (C:\Users\Developer\Documents\padawan01\plural-sight\node-express\library\node_modules\express\lib\application.js:618
    at Object.<anonymous> (C:\Users\Developer\Documents\padawan01\plural-sight\node-express\library\app.js:10:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)


I´ve got this issue and I don't know why isn't working... please, help...!

**Comment by alexandra1030** [comment]
@IlseMagali 
maybe port number 3000 is using on your other project. please change the port number.
there are many ways to change it.
for example, `npm run dev --port another number`
or you can change it in index file in config.

**Comment by adityatom** [comment]
C:\Users\Aditya\Desktop\notes-node>node app.js remove --title="secrets"
Starting app.js
Starting notes.js
Command: remove
Yargs { _: [ 'remove' ], title: 'secrets', '$0': 'app.js' }
Removing Note secrets

C:\Users\Aditya\Desktop\notes-node>nodemon app.js
[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

C:\Users\Aditya\Desktop\notes-node>

//Please help how to resolve this issue

**Comment by abbasashraf** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

// please help me how can i fix this

**Comment by khushi84throne** [comment]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (C:\Users\khushi throne\Desktop\Master Project-Udemy\                                                                                                                webserver\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (C:\Users\khushi throne\Desktop\Master Project-Udemy\w                                                                                                                ebserver\app.js:38:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
[nodemon] app crashed - waiting for file changes before starting...

Anyone kindly help me of this 
im really sick of this

**Comment by montymxb** [comment]
@khushi84throne `Error: listen EADDRINUSE :::3000`. The port you're trying to bind to is already in use by another program. Take a look at the comments above so you can clear it or change the port you're binding to.

**Comment by Dokaw2017** [comment]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by montymxb** [comment]
Considering that this issue was already resolved in the particular context of attempting to start the dashboard when the port was already in use I'm locking this. There's been a lot of useful information in this thread, but it seems some of the more recent comments would be better suited as separate issues with further details so we can focus on each one individually.

If you're still having an issue with an unhandled error being thrown please open up another thread with details there. We'll be happy to take a look at it there.
