### ISSUE TITLE
Uncaught Error: Cannot use the Master Key, it has not been provided.

### ISSUE THREAD

**Issue by arckdash** [ParsePlatform/parse-dashboard#606]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.20 of Parse Dashboard.

- [x] You're running version >=2.2.24 of Parse Server.
// I'm using parse-server-example and it has defined into the package.json a dependency to parses-server: "*", so I'm guessing that it always use the latest version.
here more details:
parse-server-example/package.json
{
  "name": "parse-server-example",
  "version": "1.4.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.8.0",
    "parse-server": "*"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
I've an elastic beanstalk with a parse-server-example up and running, I already did test of connections from different platforms and also using postman and everything seems work fine.

But when I'm trying to run the parse-dashboard from my localhost (connected to my elasticbeanstalk) I'm getting the error detailed below. I've no idea what is the error and how to fix it. Any idea would be useful.

// Localhost
parse-dashboard/Parse-dashboard/parse-dashboard-config.json
{
  "apps": [
    {
      "serverURL": "http://url_to_my_elasticbeanstalk/parse",   // NOTE: This is exactly the url that I've defined.
      "appId": "xxxxxxxxxx",
      "masterKey": "xxxxxxxxxxxxx",
      "appName": "xxxxxxxx"
    }
  ]
}

#### Steps to reproduce
commands to start parse-dashboard:
cd parse-dashboard/Parse-dashboard
parse-dashboard --config parse-dashboard-config.json
[cmd]Console output: 
The dashboard is now available at http://0.0.0.0:4040/

[browser]Console output:  // clearly I've defined the Master key, and of course is the same one that I have defined on my server.

Uncaught Error: Cannot use the Master Key, it has not been provided.
    at request (http://localhost:4040/bundles/dashboard.bundle.js:47:27278)
    at Object.g._request (http://localhost:4040/bundles/dashboard.bundle.js:47:21590)
    at e.value (http://localhost:4040/bundles/dashboard.bundle.js:1:21353)
    at http://localhost:4040/bundles/dashboard.bundle.js:33:22423
    at Array.map (native)
    at e.<anonymous> (http://localhost:4040/bundles/dashboard.bundle.js:33:22266)
    at e.s (http://localhost:4040/bundles/dashboard.bundle.js:4:27607)
    at e.value (http://localhost:4040/bundles/dashboard.bundle.js:4:26967)
    at XMLHttpRequest.i.onload (http://localhost:4040/bundles/dashboard.bundle.js:5:6995)
Running Ginger Widget  version 0.1.0.608

Any idea ? 
Thanks!

**Comment by arckdash** [comment]
I don't know why the command:

**parse-dashboard --config parse-dashboard-config.json** 

doesn't work anymore, but I just used this one instead:

**parse-dashboard --appId yourAppId --masterKey yourMasterKey --serverURL "https://example.com/parse" --appName optionalName**

and everything is working now!
