### ISSUE TITLE
events.js:160 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by cmzz** [ParsePlatform/parse-dashboard#613]
```
my-project npm run dev

> my-project@0.0.0 dev /Users/zyxcba/www/electron-projects/my-project
> node tasks/runner.js

Starting webpack-dev-server...

webpack  events.js:160
               throw er; // Unhandled 'error' event
               ^

         Error: listen EADDRNOTAVAIL 192.168.33.10:19081
             at Object.exports._errnoException (util.js:1022:11)
             at exports._exceptionWithHostPort (util.js:1045:20)
             at Server._listen2 (net.js:1249:19)
             at listen (net.js:1298:10)
             at doListening (net.js:1397:7)
             at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
             at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```

```
➜  my-project lsof -i:19081
➜  my-project
```

What's wrong!..

**Comment by flovilmart** [comment]
See: http://www.toptip.ca/2010/02/linux-eaddrnotavail-address-not.html

**Comment by Simone-cogno** [comment]
@cmzz Did you found a solution to this? I have the same problem and didn't find anything that really solved it.

**Comment by Simone-cogno** [comment]
Still have the same problem. I think I had to reastart the server last time to solve it. Does anyone have a solution to this? I'm starting the dashboard on the default port 4040...

**Comment by davimacedo** [comment]
Do you mind to open a new issue and share all details of your environment and how you are initializing the Parse Dashboard?
