### ISSUE TITLE
npm ERR! @ dashboard: `node ./Parse-Dashboard/index.js & webpack --config build.config.js --progress --watch`

### ISSUE THREAD

**Issue by trikiano** [ParsePlatform/parse-dashboard#67]
root@ks3270774 [~/parse-dashboard]# npm run dashboard

> @ dashboard /root/parse-dashboard
> node ./Parse-Dashboard/index.js & webpack --config build.config.js --progress --watch

/root/parse-dashboard/Parse-Dashboard/index.js:34
  .then(config => {
                ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

/root/parse-dashboard/plugins/svg-prep.js:10
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/parse-dashboard/base.config.js:11:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! @ dashboard: `node ./Parse-Dashboard/index.js & webpack --config build.config.js --progress --watch`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the @ dashboard script.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./Parse-Dashboard/index.js & webpack --config build.config.js --progress --watch
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.8.13-xxxx-grs-ipv6-64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dashboard"
npm ERR! cwd /root/parse-dashboard
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/parse-dashboard/npm-debug.log
npm ERR! not ok code 0
root@ks3270774 [~/parse-dashboard]#

**Comment by trikiano** [comment]
problem after `npm run dashboard`

**Comment by flovilmart** [comment]
It's likely your version of node is too old, update to >= 4.3

**Comment by trikiano** [comment]
Parse Dashboard can only be remotely accessed via HTTPS

**Comment by drew-gross** [comment]
Yes, that is to prevent accidental leakage of your master key over http. I'm going to close this, as it sounds like the original problem has been resolved.
